---
# tasks file for roles/nginx
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Allow HTTP traffic
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow HTTPS traffic
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Reload UFW
  command: ufw reload
