---
# tasks file for roles/api

- name: Pull Docker image
  docker_image:
    name: "{{ docker_image_name }}"
    source: pull

- name: Run container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image_name }}"
    state: started
    ports:
      - "{{ host_port }}:{{ container_port }}"
